/**
 * 
 */
package repast.model.agrosuccess;

import java.util.Arrays;
import java.util.List;
import me.ajlane.geo.repast.seeddispersal.SeedDispersalParams;
import me.ajlane.geo.repast.seeddispersal.SeedViabilityParams;
import me.ajlane.geo.repast.soilmoisture.SoilMoistureParams;
import repast.simphony.parameter.Parameters;

/**
 * <p>
 * Given a set of parameters generated by Repast Simphony in the course of parsing parameters.xml
 * this class will bundle up parameters corresponding xParams classes ready for consumption in 
 * the model classes which need them.
 * </p>
 * 
 * <p>
 * The parameters which <em>must</em> be specified in the {@code repast.simphony.parameter.Parameters} 
 * object passed to the constructor are as follows:
 * </p>
 * 
 * <p><b>Seed longevity parameters</b></p>
 * <ul>
 * <li>{@code oakSeedLifetime} (Oak seed lifetime)</li>
 * <li>{@code pineSeedLifetime} (Pine seed lifetime)</li>
 * <li>{@code deciduousSeedLifetime} (Deciduous seed lifetime)</li>
 * </ul>
 * 
 * <p><b>Seed dispersal parameters</b></p>
 * <ul>
 * <li>{@code acornLocationParam} (Acorn location parameter)</li>
 * <li>{@code acornScaleParam} (Acorn scale parameter)</li>
 * <li>{@code acornMaxLognormalDist} (Max lognormal acorn dispersal distance)</li>
 * <li>{@code windDistDecreaseParam} (Wind distance decrease parameter)</li>
 * <li>{@code windMinExpDist} (Wind minimum exponential dispersal probability distance)</li>
 * <li>{@code windMaxExpDist} (Wind maximum exponential dispersal probability distance)</li>
 * </ul>
 * 
 * <p><b>Soil moisture parameters</b></p>
 * <ul>
 * <li>{@code mesicThreshold} (Mesic soil moisture threshold)</li>
 * <li>{@code hydricThreshold} (Hydric soil moisture threshold)</li>
 * </ul>
 * 
 * TODO In future it might be useful to have this class -- or a descendent of it -- implement 
 * AnthroModelParams (providing access to anthropogenic model patrameters) in addition to the 
 * EnvrModelParams already provided.
 * 
 * TODO A future development might also add a WildFireParams interface
 *  
 * @author Andrew Lane
 *
 */
public class ModelParamsRepastParser implements EnvrModelParams {
  
  private static List<String> expectedParams = Arrays.asList("oakSeedLifetime", "pineSeedLifetime", 
      "deciduousSeedLifetime", "acornLocationParam", "acornScaleParam", "acornMaxLognormalDist", 
      "windDistDecreaseParam", "windMinExpDist", "windMaxExpDist", "mesicThreshold", 
      "hydricThreshold");
  
  private Parameters repastParams;
    
  ModelParamsRepastParser(Parameters repastParams) {
    // if not checkAllExpectedParamsAvailable(Parameters repastParams) raise IllegalStateException
    
    this.repastParams = repastParams;
    
  }
  
  private boolean checkAllExpectedParamsAvailable(Parameters repastParams) {
    return false;
    
  }
  
  /* (non-Javadoc)
   * @see repast.model.agrosuccess.ModelParams#getSeedDispersalParams()
   */
  @Override
  public SeedDispersalParams getSeedDispersalParams() {
    // TODO Auto-generated method stub
    return null;
  }

  /* (non-Javadoc)
   * @see repast.model.agrosuccess.ModelParams#getSeedViabilityParams()
   */
  @Override
  public SeedViabilityParams getSeedViabilityParams() {
    // TODO Auto-generated method stub
    return null;
  }

  /* (non-Javadoc)
   * @see repast.model.agrosuccess.ModelParams#getSoilMoistureParams()
   */
  @Override
  public SoilMoistureParams getSoilMoistureParams() {
    // TODO Auto-generated method stub
    return null;
  }

}
